# Docker Compose for SnapConnect Bot Scheduler
# 
# Usage:
# docker-compose -f docker-compose.scheduler.yml up -d

version: '3.8'

services:
  bot-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: snapconnect-bot-scheduler
    restart: unless-stopped
    
    environment:
      - NODE_ENV=production
      - TZ=America/New_York
      
    env_file:
      - .env
      
    volumes:
      # Persist logs
      - ./logs:/app/logs
      
    networks:
      - snapconnect-bots
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  snapconnect-bots:
    driver: bridge

volumes:
  bot-logs:
    driver: local